CRITICAL - 2022-01-06 02:03:26 --> syntax error, unexpected token "echo"
#0 C:\xampp\htdocs\cig4\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('auth/users_edit...', Array, true)
#2 C:\xampp\htdocs\cig4\app\Controllers\pages.php(73): view('auth/users_edit...')
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Pages->useredit('7')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-06 02:22:15 --> syntax error, unexpected identifier "S", expecting ")"
#0 C:\xampp\htdocs\cig4\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('auth/users_edit...', Array, true)
#2 C:\xampp\htdocs\cig4\app\Controllers\pages.php(73): view('auth/users_edit...')
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Pages->useredit('7')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-06 03:32:21 --> syntax error, unexpected token "echo"
#0 C:\xampp\htdocs\cig4\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('auth/users_edit...', Array, true)
#2 C:\xampp\htdocs\cig4\app\Controllers\pages.php(73): view('auth/users_edit...')
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Pages->useredit('8')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-06 03:33:56 --> syntax error, unexpected token "echo"
#0 C:\xampp\htdocs\cig4\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('auth/users_edit...', Array, true)
#2 C:\xampp\htdocs\cig4\app\Controllers\pages.php(73): view('auth/users_edit...')
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Pages->useredit('8')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-06 03:33:58 --> syntax error, unexpected token "echo"
#0 C:\xampp\htdocs\cig4\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('auth/users_edit...', Array, true)
#2 C:\xampp\htdocs\cig4\app\Controllers\pages.php(73): view('auth/users_edit...')
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Pages->useredit('8')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-06 03:37:31 --> syntax error, unexpected double-quoted string ">", expecting "," or ";"
#0 C:\xampp\htdocs\cig4\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('auth/users_edit...', Array, true)
#2 C:\xampp\htdocs\cig4\app\Controllers\Auth.php(202): view('auth/users_edit...', Array)
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->user_edit('7')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-06 04:58:53 --> syntax error, unexpected token "=", expecting ")"
#0 C:\xampp\htdocs\cig4\system\Router\Router.php(176): CodeIgniter\Router\Router->autoRoute('auth/addsubcate...')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(718): CodeIgniter\Router\Router->handle('auth/addsubcate...')
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(359): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-01-06 04:59:27 --> syntax error, unexpected token "}"
#0 C:\xampp\htdocs\cig4\system\Router\Router.php(176): CodeIgniter\Router\Router->autoRoute('auth/addsubcate...')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(718): CodeIgniter\Router\Router->handle('auth/addsubcate...')
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(359): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-01-06 04:59:37 --> syntax error, unexpected variable "$addsubcategory"
#0 C:\xampp\htdocs\cig4\system\Router\Router.php(176): CodeIgniter\Router\Router->autoRoute('auth/addsubcate...')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(718): CodeIgniter\Router\Router->handle('auth/addsubcate...')
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(359): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-01-06 10:52:43 --> Undefined property: stdClass::$subcategeory_id
#0 C:\xampp\htdocs\cig4\app\Views\auth\subcategory_show.php(141): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 141)
#1 C:\xampp\htdocs\cig4\system\View\View.php(214): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\cig4\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('auth/subcategor...', Array, true)
#4 C:\xampp\htdocs\cig4\app\Controllers\pages.php(67): view('auth/subcategor...')
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Pages->subcategoryshow()
#6 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#7 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-01-06 10:53:34 --> Invalid file: Pages/editCategory.php
#0 C:\xampp\htdocs\cig4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Pages/editCateg...')
#1 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('Pages/editCateg...', Array, true)
#2 C:\xampp\htdocs\cig4\app\Controllers\Auth.php(401): view('Pages/editCateg...', Array)
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->update('1')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-06 10:54:36 --> Invalid file: Pages/editCategory.php
#0 C:\xampp\htdocs\cig4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Pages/editCateg...')
#1 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('Pages/editCateg...', Array, true)
#2 C:\xampp\htdocs\cig4\app\Controllers\Auth.php(401): view('Pages/editCateg...', Array)
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->update('1')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-06 10:56:46 --> Invalid file: Pages/ editSubcategory.php
#0 C:\xampp\htdocs\cig4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Pages/ editSubc...')
#1 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('Pages/ editSubc...', Array, true)
#2 C:\xampp\htdocs\cig4\app\Controllers\Auth.php(531): view('Pages/ editSubc...', Array)
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->subupdate('2')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-06 10:57:52 --> Invalid file: Pages/editSubcategory.php
#0 C:\xampp\htdocs\cig4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('Pages/editSubca...')
#1 C:\xampp\htdocs\cig4\system\Common.php(1097): CodeIgniter\View\View->render('Pages/editSubca...', Array, true)
#2 C:\xampp\htdocs\cig4\app\Controllers\Auth.php(531): view('Pages/editSubca...', Array)
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->subupdate('2')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#5 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2022-01-06 11:09:18 --> Too few arguments to function App\Controllers\Auth::subupdate(), 0 passed in C:\xampp\htdocs\cig4\system\CodeIgniter.php on line 824 and exactly 1 expected
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->subupdate()
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-01-06 11:09:49 --> Too few arguments to function App\Controllers\Auth::subupdate(), 0 passed in C:\xampp\htdocs\cig4\system\CodeIgniter.php on line 824 and exactly 1 expected
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->subupdate()
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-01-06 11:10:35 --> Too few arguments to function App\Controllers\Auth::subupdate(), 0 passed in C:\xampp\htdocs\cig4\system\CodeIgniter.php on line 824 and exactly 1 expected
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->subupdate()
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
ERROR - 2022-01-06 11:11:23 --> Cannot add or update a child row: a foreign key constraint fails (`ecommerce`.`tbl_subcategories`, CONSTRAINT `tbl_subcategories_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `tbl_categories` (`category_id`) ON DELETE NO ACTION ON UPDATE CASCADE)
CRITICAL - 2022-01-06 11:11:23 --> Cannot add or update a child row: a foreign key constraint fails (`ecommerce`.`tbl_subcategories`, CONSTRAINT `tbl_subcategories_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `tbl_categories` (`category_id`) ON DELETE NO ACTION ON UPDATE CASCADE)
#0 C:\xampp\htdocs\cig4\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `tb...', 0)
#1 C:\xampp\htdocs\cig4\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `tb...')
#2 C:\xampp\htdocs\cig4\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `tb...')
#3 C:\xampp\htdocs\cig4\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO `tb...', Array, false)
#4 C:\xampp\htdocs\cig4\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\cig4\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\cig4\system\Model.php(620): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\cig4\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\cig4\app\Controllers\Auth.php(542): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->subupdate()
#10 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#11 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2022-01-06 11:11:49 --> Too few arguments to function App\Controllers\Auth::subupdate(), 0 passed in C:\xampp\htdocs\cig4\system\CodeIgniter.php on line 824 and exactly 1 expected
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->subupdate()
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-01-06 11:11:56 --> Too few arguments to function App\Controllers\Auth::subupdate(), 0 passed in C:\xampp\htdocs\cig4\system\CodeIgniter.php on line 824 and exactly 1 expected
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Auth->subupdate()
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-01-06 11:18:30 --> CodeIgniter\BaseModel::findAll(): Argument #1 ($limit) must be of type int, string given, called in C:\xampp\htdocs\cig4\app\Controllers\listmale.php on line 12
#0 C:\xampp\htdocs\cig4\app\Controllers\listmale.php(12): CodeIgniter\BaseModel->findAll('male')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\Listmale->index()
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Listmale))
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#6 {main}
CRITICAL - 2022-01-06 12:19:32 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 15:11:45 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 15:12:43 --> Namespace declaration statement has to be the very first statement or after any declare call in the script
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 15:13:54 --> Class "App\Libraries\Oauth" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\User->login()
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-01-06 15:18:54 --> Class "OAuth2\Storage\Pdo" not found
#0 C:\xampp\htdocs\cig4\app\Libraries\Oauth.php(10): App\libraries\Oauth->init()
#1 C:\xampp\htdocs\cig4\app\Controllers\user.php(14): App\libraries\Oauth->__construct()
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\User->login()
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-01-06 15:19:03 --> Class "OAuth2\Storage\Pdo" not found
#0 C:\xampp\htdocs\cig4\app\Libraries\Oauth.php(11): App\libraries\Oauth->init()
#1 C:\xampp\htdocs\cig4\app\Controllers\user.php(14): App\libraries\Oauth->__construct()
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\User->login()
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-01-06 15:19:05 --> Class "OAuth2\Storage\Pdo" not found
#0 C:\xampp\htdocs\cig4\app\Libraries\Oauth.php(11): App\libraries\Oauth->init()
#1 C:\xampp\htdocs\cig4\app\Controllers\user.php(14): App\libraries\Oauth->__construct()
#2 C:\xampp\htdocs\cig4\system\CodeIgniter.php(824): App\Controllers\User->login()
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-01-06 16:04:01 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cig4\system\Debug\Exceptions.php:293
Stack trace:
#0 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(293): abs('42S02')
#1 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(97): CodeIgniter\Debug\Exceptions->determineCodes(Object(PDOException))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(PDOException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 16:55:44 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cig4\system\Debug\Exceptions.php:293
Stack trace:
#0 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(293): abs('42S02')
#1 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(97): CodeIgniter\Debug\Exceptions->determineCodes(Object(PDOException))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(PDOException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 17:02:08 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cig4\system\Debug\Exceptions.php:293
Stack trace:
#0 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(293): abs('42S02')
#1 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(97): CodeIgniter\Debug\Exceptions->determineCodes(Object(PDOException))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(PDOException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 17:02:24 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cig4\system\Debug\Exceptions.php:293
Stack trace:
#0 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(293): abs('42S02')
#1 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(97): CodeIgniter\Debug\Exceptions->determineCodes(Object(PDOException))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(PDOException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 17:13:15 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cig4\system\Debug\Exceptions.php:293
Stack trace:
#0 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(293): abs('42S02')
#1 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(97): CodeIgniter\Debug\Exceptions->determineCodes(Object(PDOException))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(PDOException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 17:13:18 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cig4\system\Debug\Exceptions.php:293
Stack trace:
#0 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(293): abs('42S02')
#1 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(97): CodeIgniter\Debug\Exceptions->determineCodes(Object(PDOException))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(PDOException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 17:13:27 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cig4\system\Debug\Exceptions.php:293
Stack trace:
#0 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(293): abs('42S02')
#1 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(97): CodeIgniter\Debug\Exceptions->determineCodes(Object(PDOException))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(PDOException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 17:13:29 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cig4\system\Debug\Exceptions.php:293
Stack trace:
#0 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(293): abs('42S02')
#1 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(97): CodeIgniter\Debug\Exceptions->determineCodes(Object(PDOException))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(PDOException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 17:22:13 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cig4\system\Debug\Exceptions.php:293
Stack trace:
#0 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(293): abs('42S02')
#1 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(97): CodeIgniter\Debug\Exceptions->determineCodes(Object(PDOException))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(PDOException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 17:22:32 --> Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in C:\xampp\htdocs\cig4\system\Debug\Exceptions.php:293
Stack trace:
#0 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(293): abs('42S02')
#1 C:\xampp\htdocs\cig4\system\Debug\Exceptions.php(97): CodeIgniter\Debug\Exceptions->determineCodes(Object(PDOException))
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(PDOException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 17:58:09 --> OathFilter filter must have a matching alias defined.
#0 C:\xampp\htdocs\cig4\system\Filters\Filters.php(496): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('OathFilter')
#1 C:\xampp\htdocs\cig4\system\Filters\Filters.php(243): CodeIgniter\Filters\Filters->processAliasesToClass('before')
#2 C:\xampp\htdocs\cig4\system\Filters\Filters.php(163): CodeIgniter\Filters\Filters->initialize('listusers')
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-01-06 17:58:47 --> Oathfilter filter must have a matching alias defined.
#0 C:\xampp\htdocs\cig4\system\Filters\Filters.php(496): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('Oathfilter')
#1 C:\xampp\htdocs\cig4\system\Filters\Filters.php(243): CodeIgniter\Filters\Filters->processAliasesToClass('before')
#2 C:\xampp\htdocs\cig4\system\Filters\Filters.php(163): CodeIgniter\Filters\Filters->initialize('listusers')
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-01-06 17:59:18 --> Oathfilter filter must have a matching alias defined.
#0 C:\xampp\htdocs\cig4\system\Filters\Filters.php(496): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('Oathfilter')
#1 C:\xampp\htdocs\cig4\system\Filters\Filters.php(243): CodeIgniter\Filters\Filters->processAliasesToClass('before')
#2 C:\xampp\htdocs\cig4\system\Filters\Filters.php(163): CodeIgniter\Filters\Filters->initialize('listusers')
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2022-01-06 17:59:32 --> Class "Config\OathFilter" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-01-06 17:59:34 --> Class "Config\OathFilter" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-01-06 18:00:40 --> Declaration of App\Filters\OauthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 18:02:14 --> Declaration of App\Filters\OauthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 18:02:16 --> Declaration of App\Filters\OauthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 18:02:41 --> Class "Config\OauthFilter" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-01-06 18:03:04 --> Class "Config\OauthFilter" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-01-06 18:04:15 --> Class "CodeIgniter\Filters\OauthFilter" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-01-06 18:05:23 --> Class "CodeIgniter\Filters\OauthFilter" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-01-06 18:07:03 --> Class "CodeIgniter\Filters\OauthFilter" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-01-06 18:07:14 --> Class "CodeIgniter\Filters\OauthFilter" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-01-06 18:09:57 --> Class "CodeIgniter\Filters\OauthFilter" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-01-06 18:11:12 --> Class "CodeIgniter\Filters\OauthFilter" not found
#0 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#1 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#2 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#3 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#4 {main}
CRITICAL - 2022-01-06 18:14:37 --> Declaration of App\Filters\OauthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 18:17:00 --> Declaration of App\Filters\OauthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 18:19:01 --> Declaration of App\Filters\OauthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 18:22:16 --> Declaration of App\Filters\OauthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 18:23:55 --> Declaration of App\Filters\OauthFilter::before(CodeIgniter\HTTP\RequestInterface $request) must be compatible with CodeIgniter\Filters\FilterInterface::before(CodeIgniter\HTTP\RequestInterface $request, $arguments = null)
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-01-06 18:28:31 --> syntax error, unexpected variable "$arguments", expecting ")"
#0 C:\xampp\htdocs\cig4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\cig4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Filters\\Oau...')
#2 C:\xampp\htdocs\cig4\system\Filters\Filters.php(166): CodeIgniter\Autoloader\Autoloader->loadClass('App\\Filters\\Oau...')
#3 C:\xampp\htdocs\cig4\system\CodeIgniter.php(384): CodeIgniter\Filters\Filters->run('listusers', 'before')
#4 C:\xampp\htdocs\cig4\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cig4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cig4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#7 {main}
